[package]
name = "fp-storage"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io"]
edition = "2021"
license = "Apache-2.0"
description = "Storage primitives for Ethereum RPC (web3) compatibility layer for Substrate."
repository = "https://github.com/paritytech/frontier/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ethereum = { version = "0.12.0", features = ["with-codec"], default-features = false }
serde = { version = "1.0", features = ["derive"], optional = true }

# Frontier
fp-rpc = { path = "../rpc", default-features = false }

# Parity
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
ethereum-types = { version = "0.13.1", default-features = false }

# Substrate
sp-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-runtime = { version = "6.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-std = { version = "4.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

[features]
default = ["std"]
std = [
	"ethereum/std",
	"serde",
	# Frontier
	"fp-rpc/std",
	# Parity
	"codec/std",
	"ethereum-types/std",
	# Substrate
	"sp-api/std",
	"sp-runtime/std",
]
