[package]
name = "fp-storage"
version = "2.0.0"
license = "Apache-2.0"
description = "Storage primitives for Ethereum RPC (web3) compatibility layer for Substrate."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ethereum = { workspace = true }
serde = { workspace = true, optional = true }

# Frontier
fp-rpc = { workspace = true }

# Parity
ethereum-types = { workspace = true }
scale-codec = { package = "parity-scale-codec", workspace = true }

# Substrate
sp-api = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
	"ethereum/std",
	"serde",
	# Frontier
	"fp-rpc/std",
	# Parity
	"scale-codec/std",
	"ethereum-types/std",
	# Substrate
	"sp-api/std",
	"sp-runtime/std",
]
